ngscopeclient/scopehal-apps

- glscopeclient/CMakeLists.txt
- glscopeclient/HistoryWindow.cpp
- glscopeclient/OscilloscopeWindow.cpp
- glscopeclient/ScopeSyncWizard.cpp
- glscopeclient/WaveformArea.cpp
- glscopeclient/WaveformArea.h
- glscopeclient/WaveformArea_cairo.cpp
- glscopeclient/glscopeclient.h
- glscopeclient/main.cpp
Currently, saving is disabled on Windows. Will be implemented in a future PR.
> Allow compilation and offline execution of glscopeclient on Windows

- glscopeclient/CMakeLists.txt
- glscopeclient/OscilloscopeWindow.cpp
- glscopeclient/OscilloscopeWindow.h
- glscopeclient/Preference.cpp
- glscopeclient/PreferenceDialog.cpp
- glscopeclient/PreferenceDialog.h
- glscopeclient/PreferenceManager.cpp
- glscopeclient/PreferenceManager.h
This PR contains a basic, bad looking implementation of the preferences dialog. Further PRs will improve its design (Issue #121)
> Basic implementation of the preferences dialog

- src/glscopeclient/CMakeLists.txt
- src/glscopeclient/OscilloscopeWindow.cpp
- src/glscopeclient/OscilloscopeWindow.h
- src/glscopeclient/Preference.cpp
- src/glscopeclient/Preference.h
- src/glscopeclient/PreferenceDialog.cpp
- src/glscopeclient/PreferenceDialog.h
- src/glscopeclient/PreferenceManager.cpp
- src/glscopeclient/PreferenceManager.h
- src/glscopeclient/main.cpp
This was needed as master couldn't be merged into gui-dev cleanly due to the
submodule refactoring.
Note that this will become a replacement for the old gui-dev branch.
> Migrate the gui-dev changes to a gui-dev-new branch.

- src/glscopeclient/OscilloscopeWindow.cpp
Refactor usleep(..) by std::this_thread::sleep_for(std::chrono::microseconds(..))
> Refactor usleep()

- .github/workflows/build.yml
Add a Windows build target to the GitHub Actions workflow.
> Enable Windows build in GitHub Actions

- src/glscopeclient/Preference.cpp
- src/glscopeclient/Preference.h
- src/glscopeclient/PreferenceDialog.cpp
- src/glscopeclient/PreferenceManager.cpp
- src/glscopeclient/PreferenceTree.cpp
- src/glscopeclient/PreferenceTree.h
> Implemented visibility support for preferences

- src/glscopeclient/Preference.cpp
- src/glscopeclient/Preference.h
- src/glscopeclient/PreferenceDialog.cpp
- src/glscopeclient/PreferenceManager.cpp
> Implemented units in the preferences system and preferences GUI

- src/glscopeclient/Preference.cpp
- src/glscopeclient/Preference.h
- src/glscopeclient/PreferenceDialog.cpp
- src/glscopeclient/PreferenceDialog.h
- src/glscopeclient/PreferenceManager.h
- src/glscopeclient/PreferenceSchema.cpp
- src/glscopeclient/PreferenceTree.cpp
> Implemented enum preferences

- src/glscopeclient/Preference.cpp
- src/glscopeclient/Preference.h
- src/glscopeclient/PreferenceDialog.cpp
- src/glscopeclient/PreferenceDialog.h
- src/glscopeclient/PreferenceManager.cpp
- src/glscopeclient/PreferenceManager.h
- src/glscopeclient/PreferenceSchema.cpp
- src/glscopeclient/PreferenceTree.cpp
- The implementation of the preferences dialog is no longer a big mess :)
- The preferences system does now support font preferences
> Refactored preference dialog internals and implemented font support

- src/examples/usbcsv/main.cpp
This program was originally created by azonenberg to assist in
decoding USB snippets in a headless state. The main intent of this
program is to export only packets sent from the client device
to the host computer. It is a bit messy, but I tried to make
it clear how the logic works.
The output format is as follows:
[starting line in csv] [ending line in csv] [DATA 1/0] [hex bits] | [SETUP request code]
This is supposed to make it easier to extract those client packets
from the CSV. I briefly considered using CPython to transform it
into a format that can easily be used in feature extraction libraries,
but that is more work than is necessary.
This is not a perfect example, as I only really capture the data
packets and the NAK packets. There are others in the USB spec,
so feel free to …
> Improve the usbcsv example

- .github/workflows/build.yml
This PR includes several updates to the CI workflow.
Refs msys2/MINGW-packages#8676 azonenberg/scopehal-docs#28
> CI workflow updates

- src/glscopeclient/CMakeLists.txt
- src/glscopeclient/WaveformProcessingThread.cpp
- src/glscopeclient/glscopeclient.h
- src/glscopeclient/main.cpp
- src/glscopeclient/pthread_compat.cpp
- src/glscopeclient/pthread_compat.h
> fix BSD build support (#345)

- src/glscopeclient/CMakeLists.txt
- src/glscopeclient/OscilloscopeWindow.cpp
- src/glscopeclient/PreferenceManager.cpp
Fix windows/mingw build issues identified in https://github.com/azonenberg/scopehal/issues/502
Should also pull matching PR in scopehal https://github.com/azonenberg/scopehal/pull/503 and update the submodule for scopehal.
> Windows fixes

- src/glscopeclient/Rect.h
- src/glscopeclient/WaveformArea.h
- src/glscopeclient/WaveformArea_cairo.cpp
goes-with https://github.com/glscopeclient/scopehal/pull/595
> Support displaying clipping warning

- src/glscopeclient/HaltConditionsDialog.cpp
- src/glscopeclient/OscilloscopeWindow.cpp
- src/glscopeclient/WaveformArea_cairo.cpp
Merge with https://github.com/glscopeclient/scopehal/pull/669
> Refactor GetText/GetColor to be properties on protocol waveforms

- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows.yml
- .github/workflows/build.yml
- cmake/FindPackageHandleStandardArgs.cmake
- cmake/FindPackageMessage.cmake
- cmake/FindVulkan.cmake
- src/glscopeclient/CMakeLists.txt
Fix issue https://github.com/glscopeclient/scopehal-apps/issues/474 "Linux CI build is broken because it can't find glslc"
- Build-ubuntu => Build OK (Fail `Run Tests`)
- See https://github.com/glscopeclient/scopehal-apps/runs/8141307741?check_suite_focus=true#step:8:11 
Fix issue https://github.com/glscopeclient/scopehal-apps/issues/470 "Windows CI build is broken despite finding Vulkan SDK"
- Build-windows => Build OK (Fail `Test`)
- See https://github.com/glscopeclient/scopehal-apps/runs/8141307323
This PR requires also https://github.com/glscopeclient/scopehal/pull/674
> Fix GitHub workflows Build for ubuntu-latest & windows-latest(MSYS2/MINGW64)

- CMakeLists.txt
- src/glscopeclient/ScopeSyncWizard.cpp
- src/glscopeclient/ScopeSyncWizard.h
- src/glscopeclient/WaveformArea_rendering.cpp
- src/glscopeclient/main.cpp
- tests/Filters/SubtractFilter.cpp
Necessary for glscopeclient/scopehal#455
> Building on arm64

- src/glscopeclient/WaveformArea.h
- src/glscopeclient/WaveformArea_cairo.cpp
- src/glscopeclient/WaveformArea_rendering.cpp
Also fixes longstanding bug where you had to place cursor to left of a bar on a histogram to see it's value.
> Refactor to use new helpers from scopehal for getting values

- src/glscopeclient/OscilloscopeWindow.cpp
See also https://github.com/glscopeclient/scopehal/pull/712
CI results from my fork:
Ubuntu: https://github.com/ehntoo/scopehal-apps/actions/runs/3208967520/jobs/5245294034
macOS: https://github.com/ehntoo/scopehal-apps/actions/runs/3208967523/jobs/5245294027
Windows: https://github.com/ehntoo/scopehal-apps/actions/runs/3208967521/jobs/5245294009
> Remove usage of posix APIs

- src/glscopeclient/OscilloscopeWindow.cpp
Enable only those channels already enabled on connect, except for:
- On headless scopes, enable all analog channels. Or, if no analog, all digital.
- On regular scopes, if no channels enabled, enable the first.
Persists existing behaviour for connecting the 2nd+ channel forward. Didn't want to duplicate too much code, so this is an incremental improvement only.
> Move towards unifying on-connect behaviour in glscope with ngscope

- src/glscopeclient/OscilloscopeWindow.cpp
- src/glscopeclient/OscilloscopeWindow.h
- src/glscopeclient/WaveformGroup.cpp
- src/glscopeclient/WaveformGroup.h
- src/ngscopeclient/CMakeLists.txt
> Use yaml-cpp for serialization instead of string concatenation

- src/ngscopeclient/FontManager.cpp
- src/ngscopeclient/FontManager.h
- src/ngscopeclient/MainWindow.cpp
- src/ngscopeclient/VulkanWindow.cpp
- src/ngscopeclient/VulkanWindow.h
This should be the right way, not a hack :)
> Support window content scale in ngscopeclient

- src/ngscopeclient/shaders/waveform-compute.glsl
I would definitely encourage people that had the issue to test the patch.
And others (nvidia / amd) as well to make sure it doesn't create any issues or major performance loss.
> Fix Hang on intel iGPUs

- src/ngscopeclient/FontManager.h
- src/ngscopeclient/Preference.h
Adds some more missing includes.
> Add missing includes masked by PCH

- src/ngscopeclient/FilterGraphEditor.cpp
- src/ngscopeclient/ProtocolAnalyzerDialog.cpp
- src/ngscopeclient/VulkanWindow.cpp
- src/ngscopeclient/WaveformArea.cpp
- src/ngscopeclient/WaveformGroup.cpp
This fixes scaling on macOS by taking into account the global scale parameter when accessing raw font size.
> Fix scaling on macOS

- src/ngscopeclient/MainWindow.cpp
> Fix default font not changing when font is already loaded in atlas

- src/ngscopeclient/PreferenceDialog.cpp
This allows selection of system-installed fonts on macOS and provides a sorted list.
A further improvement would be to always use the software-provided font for the font selection box, in case the user picks a font like Wingdings.
> Find all fonts and provide a sorted list

- tests/Acceleration/Buffers.cpp
This fixes the tests to properly handle https://github.com/ngscopeclient/scopehal/pull/860.
> Fix tests for unified memory

- .github/workflows/build-macos-arm.yml
- .github/workflows/build-macos-intel.yml
This should fix macOS CI. GitHub added arm64 Mac CI a few months ago.
> Fix macOS ARM and Intel CI

- src/ngscopeclient/StreamBrowserDialog.cpp
Hi Andrew,
As discussed with @jwise and you on Discord, this PR changes the PSU on/off switches to combo-based toggles to prevent accidental channel activation:
Best,
Frederic.
> PSU switch change to a combo-based toggle

- src/ngscopeclient/CMakeLists.txt
Andrew,
Here is the fix for https://github.com/ngscopeclient/scopehal-apps/issues/629
Best,
Frederic.
> Fix for spaces in Windows path
