ngscopeclient/scopehal-apps

glscopeclient/shaders/waveform-compute.glsl

This is a fix for the error :
ERROR: Compile of shader shaders/waveform-compute.glsl failed:
0:13(4): error: embedded structure declarations are not allowed
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>

glscopeclient: Fix up shader syntax to avoid embedded struct definitions

---

glscopeclient/OscilloscopeWindow.cpp

OscilloscopeWindow: set max waveform count before loading waveforms

---

glscopeclient/CMakeLists.txt
glscopeclient/OscilloscopeWindow.cpp
glscopeclient/OscilloscopeWindow.h
glscopeclient/Preference.cpp
glscopeclient/Preference.h
glscopeclient/PreferenceManager.cpp
glscopeclient/PreferenceManager.h
glscopeclient/main.cpp

This PR implements:
- The `Preference` class, which holds a single preference value and its metadata in form a sum type
- The `PreferenceManager` class which
- Manages and stores all known preferences
- Initializes them with default values
- Path handling and creation for both Windows and POSIX
- Loads existing values from disk
- Provides facilities to retrieve values by their identifier
- Allows saving of preferences back to disk
- Basic integration into `OscilloscopeWindow`

Basic preference system infrastructure

---

src/glscopeclient/glscopeclient.h

include chrono required for refactoring of usleep(..) by std::this_thread::sleep_for(std::chrono::microseconds(..))

include chrono required for refactoring of usleep

---

src/glscopeclient/OscilloscopeWindow.cpp
src/glscopeclient/OscilloscopeWindow.h
src/glscopeclient/styles/glscopeclient.css

This implements a basic help menu and modal About box using Gtk::AboutDialog, with license text and credits list, as depicted below. Note that the version number is a hardcoded TODO item with this as that's tied in with git hashes and hooking git-describe into the build harness.

Implement about box (#175)

---

src/glscopeclient/OscilloscopeWindow.cpp
src/glscopeclient/OscilloscopeWindow.h
src/glscopeclient/ScopeApp.cpp

This PR adds a `*.bin` filter to the Import File dialog for Agilent, Keysight and Rigol multi-channel binary waveform capture files.
`DoImportCSV()` and `DoImportBIN()` are very similar and could probably be refactored down into `DoFileImport()`. I didn't have any CSVs to test with so I focused on getting the BIN import working on its own.
See related PR azonenberg/scopehal#396 for BIN file parser.

Add *.bin filter to Import dialog

---

src/glscopeclient/InstrumentConnectionDialog.cpp
src/glscopeclient/main.cpp

Confusing error message when null transport is selected with no path entered - fixed by setting path to "null" in that case.
Removed siggen driver from GUI driver list because it segfaults on startup. Removed "siggen" from null transport error message.

Driver selection dialog polish

---

.github/workflows/build.yml
msys2/mingw-w64-ffts/PKGBUILD

The first commit in this PR adds a PKGBUILD recipe for building and installing FFTS, instead of doing it manually. The recipe is equivalent to the ones used upstream, but the main branch is built, instead of using a fixed commit.
Then, make install is used for packaging the MSYS2 build of scopehal-apps, instead of manually specifying the artifacts to be uploaded. The result looks almost correct, but `liblog.dll` is missing:
```
dist
└── mingw64
├── bin
│   ├── glscopeclient.exe
│   ├── libgraphwidget.dll
│   ├── libscopehal.dll
│   └── libscopeprotocols.dll
├── lib
│   ├── libgraphwidget.dll.a
│   ├── libscopehal.dll.a
│   └── libscopeprotocols.dll.a
└── share
├── applications
│   └── glscopeclient.desktop
└── glscopeclient
├── gradients
│   ├── eye-gradient-crt.rgba
│   ├── …
```

Use make install on Windows (MSYS2)

---

.github/workflows/build.yml
msys2/PKGBUILD

Instead of writing the build steps manually in the CI workflow, in this PR a PKGBUILD recipe is added. The recipe is similar to the one used in [msys2/MINGW-packages](https://github.com/msys2/MINGW-packages). However, instead of a pinned version, here the checked out version is built.
This is blocked by azonenberg/scopehal-docs#31.

ci: use msys2 recipe

---

src/glscopeclient/FilterGraphEditorWidget.cpp

When right clicking while dragging onto nothing, the selected node gets
set to NULL, but the node rendering assumes the selected node to be
valid during a drag.
The drag is now just canceled on a right click.

Fix null pointer dereference in graph editor

---

CMakeLists.txt

CMake from 3.0 on distinguishes between normal clang, and Apple's clang: https://cmake.org/cmake/help/latest/policy/CMP0025.html
So, for any clang specific flags, we need to check for both.
This depends on https://github.com/azonenberg/scopehal/pull/513 to fix all build issues I could find.

Set Clang specific parameters for Apple Clang too

---

src/glscopeclient/WaveformArea.cpp

With this change, I can start glscopeclient on my Ubuntu 21.04 laptop. I can open the demo device and display the waveforms.
It relies on the undocumented behavior that libglew is properly initialized, even though it has reported GLEW_ERROR_NO_GLX_DISPLAY.
Here's the definition glewInit for the 2.0.0 release dating back to 2016. It has stayed the same AFAICT in 2.1.0 and 2.2.0: https://github.com/nigels-com/glew/blob/glew-2.0.0/auto/src/glew_init_tail.c#L35 
I have libglew-dev 2.1.0-4 installed.
It's a hack that hopefully can be removed once GLEW 2.2.0 has trickled down through to the different distributions packet repositories. Then we can just call glewContextInit on wayland. 
Closes #277

WaveformArea: Ignore GLX errors for Wayland

---

src/glscopeclient/OscilloscopeWindow.cpp

Refresh views when scope configuration is reloaded. Both the timeline and waveforms are refreshed because changes could be in either.

Make 'reload configuation from scope' option refresh views

---

CMakeLists.txt
src/ngscopeclient/CMakeLists.txt
src/ngscopeclient/VulkanWindow.cpp
src/ngscopeclient/ngscopeclient.h
tests/Acceleration/CMakeLists.txt
tests/Filters/CMakeLists.txt
tests/Primitives/CMakeLists.txt

These changes, along with https://github.com/glscopeclient/scopehal/pull/687 are sufficient to get both `ngscopeclient` launching and running on my M1 Max MacBook Pro using clang-14 from homebrew. Very limited testing has been done so far.
There are some issues with FFTS (as guessed in https://github.com/glscopeclient/scopehal/issues/685#issuecomment-1242894685), but tests are all green when the various instances of `g_gpuFilterEnabled = false` are commented out.

macOS fixes

---

src/ngscopeclient/CMakeLists.txt
src/ngscopeclient/PowerSupplyDialog.cpp

This PR leverages the new feature detection functions added by https://github.com/glscopeclient/scopehal/pull/691 to conditionally show/hide subsections of the power supply dialog.
Additionally, it fixes a bug where the "Apply" button for a power supply channel's "Current" setting was mapped to the `SetPowerVoltage` rather than `SetPowerCurrent` method.

ngscopeclient Power Supply Feature Detection

---

.github/workflows/build-macos.yml
CMakeLists.txt
src/glscopeclient/ScopeSyncWizard.cpp
src/glscopeclient/ScopeSyncWizard.h

Along with https://github.com/glscopeclient/scopehal/pull/708, this PR adds a macOS CI build using the github-hosted runners. Won't get us M1/aarch64 coverage, but still a useful reference point.
Example successful run available here: https://github.com/ehntoo/scopehal-apps/actions/runs/3193904104

macOS GitHub actions CI runner

---

.github/workflows/build-windows.yml
msys2/PKGBUILD

Solved the issue by merging the two individual msi and non_msi builds into one to save disk space. This also optimized the build time quite significantly.

CI: Windows CI runner out of disk space

---

src/glscopeclient/CMakeLists.txt
src/glscopeclient/OscilloscopeWindow.cpp
src/glscopeclient/ProtocolAnalyzerWindow.cpp
src/glscopeclient/WaveformArea_cairo.cpp
src/glscopeclient/glscopeclient.h
src/ngscopeclient/Preference.h
src/ngscopeclient/main.cpp

These changes accompany https://github.com/glscopeclient/scopehal/pull/710 to refactor our usage of Gdk::Color for specifying colors within scopehal. Additionally, there are a few changes to begin to move towards being able to compile ngscopeclient without GTK.
CI results from my fork, with scopehal pointed at the last commit in https://github.com/glscopeclient/scopehal/pull/710:
Ubuntu: https://github.com/ehntoo/scopehal-apps/actions/runs/3208714570/jobs/5244820709
macOS: https://github.com/ehntoo/scopehal-apps/actions/runs/3208714571/jobs/5244820704
Windows: https://github.com/ehntoo/scopehal-apps/actions/runs/3208714569/jobs/5244820702

Migrate from Gdk::Color to HTML color strings

---

.github/workflows/build-windows.yml

Add a cache for the compiled glslang output for a ~20 minute build time savings on win32.
Before cache: https://github.com/ehntoo/scopehal-apps/actions/runs/3211866114/jobs/5250329934
After cache: https://github.com/ehntoo/scopehal-apps/actions/runs/3211866114/jobs/5250598092

Add a cache for glslang compilation on win32 CI

---

src/ngscopeclient/CMakeLists.txt

instead of a cmake glob, as the shaders are not build yet when the glob is run on a clean build.

ngscopeclient: change SPIRV_SHADERS to be an explicit list

---

src/ngscopeclient/CMakeLists.txt

This PR addresses the same issue as #537 in a slightly less repetitious fashion. The way we are constructing the `protocolshaders` target means that its CMake `SOURCES` are already the absolute paths to all the shaders. As such, we can just reference the sources list directly.

Use simpler solution for ngscopeclient shader installation

---

.github/workflows/build-ubuntu.yml
.github/workflows/build-windows.yml
src/ngscopeclient/Session.cpp

Fix build error for Windows MSYS2-Mingw64
Fix warnings on build-windows.yml & build-ubuntu.yml:
- Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/upload-artifact@v2

Fix Windows MSYS2-Mingw64-build / Fix Warnings build-windows.yml & build-ubuntu.yml

---

.github/workflows/build-ubuntu.yml
.github/workflows/build-windows.yml

Update GitHub CI build-ubuntu.yml & build-windows.yml to use VulkanSDK 1.3.250.0
Do not forget to also merge & update https://github.com/glscopeclient/scopehal-docs/pull/65

Update GitHub CI build-ubuntu.yml & build-windows.yml to use VulkanSDK 1.3.250.0

---

.github/workflows/build-ubuntu.yml
.github/workflows/build-windows.yml

Update build-ubuntu.yml &  build-windows.yml using VULKAN_SDK_VERSION 1.3.250.1 as the old one VULKAN_SDK_VERSION 1.3.250.0 is not available anymore

Update build-ubuntu.yml &  build-windows.yml using VULKAN_SDK_VERSION 1.3.250.1

---

.github/workflows/build-ubuntu.yml

Needed for latex->html conversion.

Add missing make4ht and dvipng utils to ubuntu CI

---

README.md

Added main website https://www.ngscopeclient.org
Fixed link to latest user manuals / Getting Started (on https://www.ngscopeclient.org)

Update README.md (Add website / fix User Manual to use https://www.ngscopeclient.org)

---

src/ngscopeclient/MainWindow.cpp

This fixes History and Performance Metrics menu items being greyed out after closing its respective dialog menu.

ngscopeclient: handle m_metricsDialog and m_historyDialog on dialog close

---

src/ngscopeclient/VulkanWindow.cpp

The descriptor pool needs to remain valid until we're done with ImGUI.

VulkanWindow: Releave descriptor pool after imgui cleanup

---

tests/Acceleration/main.cpp
tests/Filters/Filter_Add.cpp
tests/Filters/Filter_FFT.cpp
tests/Filters/Filter_Subtract.cpp
tests/Filters/Filter_Upsample.cpp
tests/Filters/FrequencyMeasurement.cpp
tests/Filters/main.cpp
tests/Primitives/main.cpp

This fixes #488.
Note that this may no longer be accurate:
```
//Clean up after the scope goes out of scope (pun not intended)
```

Move test initialization and teardown into Catch2 event listeners

---

tests/Acceleration/main.cpp
tests/Filters/main.cpp
tests/Primitives/main.cpp

This allows for tests to function headless as they only require Vulkan compute, not a window.

Prevent glfw init for tests as glfw requires an X/Wayland server

---

CMakeLists.txt

Trying to enable all the sanitizers is silly and won't work. This just enables AddressSanitizer and UBSan, which can be used together on GCC and Clang.

Fix build with SANITIZE

---

CMakeLists.txt
src/ngscopeclient/AboutDialog.cpp
src/ngscopeclient/BERTDialog.cpp
src/ngscopeclient/CMakeLists.txt
src/ngscopeclient/LoadDialog.cpp
src/ngscopeclient/MainWindow.cpp
src/ngscopeclient/NotesDialog.cpp
src/ngscopeclient/PowerSupplyDialog.cpp
src/ngscopeclient/Preference.cpp
src/ngscopeclient/PreferenceManager.cpp
src/ngscopeclient/PreferenceTree.cpp
src/ngscopeclient/ScopeDeskewWizard.cpp
src/ngscopeclient/Session.cpp
src/ngscopeclient/TextureManager.cpp
src/ngscopeclient/VulkanWindow.cpp
src/ngscopeclient/WaveformArea.cpp
src/ngscopeclient/WaveformThread.cpp
src/ngscopeclient/pthread_compat.cpp
tests/Acceleration/main.cpp
tests/Filters/Filter_Add.cpp
tests/Filters/Filter_DeEmbed.cpp
tests/Filters/Filter_FFT.cpp
tests/Filters/Filter_FIR.cpp
tests/Filters/Filter_Subtract.cpp
tests/Filters/Filter_Upsample.cpp
tests/Filters/main.cpp
tests/Primitives/Convert16BitSamples.cpp
tests/Primitives/Convert8BitSamples.cpp
tests/Primitives/main.cpp

This fixes nearly all current warnings. `[[maybe_unused]]` is added in some places where it makes sense. `-Werror` has been turned on for most warnings as well.
The related scopehal PR, https://github.com/ngscopeclient/scopehal/pull/854, and the related logtools PR, https://github.com/ngscopeclient/logtools/pull/14, are needed.

Fix warnings

---

src/ngscopeclient/MetricsDialog.cpp

Updates the performance metrics window to accurately show usage with unified memory (requires https://github.com/ngscopeclient/scopehal/pull/860).

Update performance metrics window for unified memory

---

src/ngscopeclient/VulkanWindow.cpp
src/ngscopeclient/VulkanWindow.h

The Intel integrated GPU on my Ivy Bridge laptop has a minimum swapchain of 4 images. I've tested this on that computer as well as on my M2 MacBook Air and it works fine.

Fix for GPUs that have a swapchain shallower or deeper than 2 images

---

src/ngscopeclient/WaveformArea.cpp
src/ngscopeclient/WaveformArea.h
src/ngscopeclient/WaveformGroup.cpp
src/ngscopeclient/WaveformGroup.h

This PR adds support for horizontally scrolling through waveforms with a horizontal scroll wheel or Shift+Scroll.
Also:
- Replaces deprecated `ImGui::SetItemUsingMouseWheel` with `ImGui::SetItemKeyOwner(ImGuiKey_MouseWheelY/X)` 
- Adds `ImGuiWindowFlags_NoScrollWithMouse` flag to the WaveformGroup to  prevent buggy horizontal scroll behaviour

Add horizontal scroll support for waveform views

---

src/ngscopeclient/CMakeLists.txt

Demo oscilloscope was crashing ngscopeclient due to the absence of "channels" directory in the installer => added with this patch.

Fix for windows installer

---

src/ngscopeclient/NFDFileBrowser.cpp

Moved to U8 version of NFDe as suggested in the documentation to fix WIN32 compilation.
https://github.com/btzy/nativefiledialog-extended : 
"The U8/u8 in NFDe refer to the API for UTF-8 characters (char), which most consumers probably want. An N/n version is also available, which uses the native character type (wchar_t on Windows and char on other platforms)."

Fixed WIN32 compilation.

---

src/ngscopeclient/PreferenceSchema.cpp
src/ngscopeclient/Session.cpp

As requested by joshua_, here is the 16bit data transfert mode for Rigol DHO models (settings part).
Tested OK on my DHO804. Should work on DHO1000/4000 as well.
I used the same default/8bit/16bit setting system as for Siglent HD models.
Goes with the companion PR on scopehal : https://github.com/ngscopeclient/scopehal/pull/900

8bit/16bit data transfer mode setting for Rigol DHO models.

---

src/ngscopeclient/InstrumentThread.cpp
src/ngscopeclient/MainWindow.cpp
src/ngscopeclient/Session.h
src/ngscopeclient/StreamBrowserDialog.cpp
src/ngscopeclient/StreamBrowserDialog.h

This is a draft PR to experiment with some UI for #760 and #761, and in general, the concept of making the StreamBrowserDialog meaningfully richer in showing instrument and system status.  Here is what I have right now:
Obviously there is going to be a lot of stuff to add and cleanup to do before this is ready to merge, and probably will include some scopehal changes, but this is the current UI metaphor set that I'm playing with.  Title bars are still draggable, for instance, but other parts are not, and I think this makes some sense.  Some things to consider at some point:

Rich UI support for StreamBrowserDialog on oscilloscopes

---

src/ngscopeclient/PreferenceSchema.cpp

Fixes an exception for me, if I try to to connect to my scope.
> Terminate called after throwing an instance of 'std::runtime_error'
>  what():  Couldnt find path segment in preference category

Fix Typo in PreferenceSchema.cpp

---

src/ngscopeclient/StreamBrowserDialog.cpp
src/ngscopeclient/TimebasePropertiesDialog.cpp
src/ngscopeclient/TimebasePropertiesDialog.h

Hi Andrew,
Here is the PR for specans:
- Adds rbw value to TimebasePropertiesDialog
- Adapts instrument properties in StreamBrowserDialog according to HasTimebaseControls() and HasFrequencyControls() values
- Adds missing PushIds that could lead to collisions when text/values were the same on two links.
A call to GetResolutionBandwidth() and GetCenterFrequency() is made in the render method of StreamBrowserDialog.
A PR will come on scopehal to make these methods cache the value for Tek driver (which is the only one that does not cache the value).
Best,
Frederic.

Specan fixes

---

.github/workflows/build-windows.yml
src/ngscopeclient/CMakeLists.txt

Hi Andrew,
Here is the PR to add support for CI build of MSI installer on Windows.
Installer is built against ucrt64 environment (since gcc is required for WiX toolset to work and clang64 does not provide gcc).
As discussed msys64 and clang64 built are still active but without the CPack part.
MSI installer and protable zip artifacts are uploaded at the end of the build.
Best,
Frederic.

CI Build for Windows MSI installer

---

.github/workflows/CodeQL.yml
.github/workflows/build-arch.yml
.github/workflows/build-debian.yml
.github/workflows/build-fedora.yml
.github/workflows/build-macos-arm.yml
.github/workflows/build-macos-intel.yml
.github/workflows/build-ubuntu.yml
.github/workflows/build-windows.yml
CMakeLists.txt
msys2/PKGBUILD
src/ngscopeclient/wix/license-paths
tests/Filters/CMakeLists.txt
tests/Filters/Filter_DeEmbed.cpp
tests/Filters/Filter_FFT.cpp

This PR closes ngscopeclient/scopehal#757
There are some things that I wasn't sure about, I will mark them inside the code comment region after the PR is submitted, the most notable is that I changed nouts to sines.size() inside the DeEmbed filter test, because otherwise ASAN complained, although the tests ran fine either way.
Windows CI started to fail, but it seems like clang is being more aggressive with some imgui internal function, in other platform it builds fine.

Migrate to FFTW from FFTS inside unit tests

---

CMakeLists.txt
src/ngscopeclient/CMakeLists.txt

Commit 4457dd5e35a1452f3fc29529aa200584e1841fcf updated imgui to a version which [pulls in](https://github.com/ngscopeclient/imgui/blob/c21de0084ca6981f1a31ed7e5f0386e6adff5cde/backends/imgui_impl_glfw.cpp#L137) GLFW's wayland implementation in a mandatory way, which requires wayland-client headers.
This builds fine on most distros, however some like openSUSE Tumbleweed  (and presumably Leap too, haven't checked) have `wayland-client.h` in a subdirectory, not in the main include path, which usally is `/usr/include`.
See output of RPM to show the directory structure on Tumbleweed:
```
rpm -ql wayland-devel
/usr/bin/wayland-scanner
/usr/include/wayland
/usr/include/wayland/wayland-client-core.h
/usr/include/wayland/wayland-client-protocol.h
/usr/include/wayland/wayland-client.h …
```

Fix imgui not building on distros which don't have wayland headers on the default include path on Linux
